[colors.primary]
background = '#141314'
foreground = '#e6e1e3'
 
[colors.cursor]
text = '#e6e1e3'
cursor = '#c9c5c7' 
 
[colors.vi_mode_cursor]
text = '#141314'
cursor = '#ccc3d5' 
 
[colors.search.matches]
foreground = '#484648' 
background = '#cdc2db' 
 
[colors.search.focused_match]
foreground = '#484648' 
background = '#ccc3d5' 
 
[colors.footer_bar]
foreground = '#484648' 
background = '#e6e1e3' 
 
[colors.hints.start]
foreground = '#484648' 
background = '#cbc4cf' 
 
[colors.hints.end]
foreground = '#484648' 
background = '#cbc4cf' 
 
[colors.selection]
text = '#141314'
background = '#ccc3d5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ccc3d5' 
yellow = '#625c6b' 
blue = '#ccc3d5' 
magenta = '#cdc2db' 
cyan = '#cbc4cf' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 